using System;using KeyMouseStats;
internal static class Release120Tests{
static void Check(bool b,string s){if(!b)throw new Exception(s);}
static void Main(){try{Run();}catch(Exception e){Console.WriteLine(e.Message);Environment.ExitCode=1;}}
static void Run(){Store.History.Clear();Store.RollDay(DateTime.Today);DayRecord day=Store.Today;day.ActiveSeconds=230;
ActiveSession a=new ActiveSession{Start=day.Date.AddHours(9),End=day.Date.AddHours(9).AddSeconds(100),Seconds=100,CrossObservedSeconds=80},b=new ActiveSession{Start=day.Date.AddHours(10),End=day.Date.AddHours(10).AddSeconds(100),Seconds=100,CrossObservedSeconds=90},old=new ActiveSession{Start=day.Date.AddHours(11),End=day.Date.AddHours(11).AddSeconds(30),Seconds=30};
a.AppSeconds[@"C:\A.exe"]=60;a.AppSeconds[@"C:\B.exe"]=10;b.AppSeconds[@"C:\A.exe"]=10;b.AppSeconds[@"C:\B.exe"]=60;day.Sessions.Add(a);day.Sessions.Add(b);day.Sessions.Add(old);
CrossReportData cross=CrossReportData.Build(day.Date,7);Check(cross.SeriesNames[0]=="A.exe"&&cross.SeriesNames[1]=="B.exe","stable application identity across sessions");Check(cross.Chart[1].Values[0]==10&&cross.Chart[2].Values[0]==60,"same color maps to same app despite different rankings");Check(cross.Chart[1].Values[3]==20&&cross.Chart[1].Values[4]==10,"unidentified and unobserved kept separate");Check(cross.Chart[0].Values[4]==30,"old session not apportioned from daily apps");foreach(CrossChartRow r in cross.Chart){double sum=0;foreach(double v in r.Values)sum+=v;Check(sum==r.Total,"session components conserve duration");}
day.ActiveSeconds=999;Check(CrossReportData.Build(day.Date,7).CardValues[3]=="60.9%","session coverage denominator excludes unrelated daily time");day.ActiveSeconds=230;
day.ComboCounts["ctrl_c"]=10;day.ComboCounts["ctrl_v"]=5;day.ComboCounts["alt_tab"]=4;day.ComboCounts["ctrl_shift_s"]=7;ShortcutSavings.MenuSeconds=2;ShortcutSavings.ShortcutSeconds=.5;ShortcutSavings.MenuClicks=2;
CrossReportData savings=ShortcutSavings.Build(day);Check(savings.CardValues[0]=="15"&&savings.Chart.Count==2,"only exact modeled combinations count");double seconds=0;foreach(CrossChartRow r in savings.Chart)seconds+=r.Values[0];Check(seconds==22.5,"time model applied once per action");Check(savings.Rows.Count==4&&savings.CardValues[1]=="≈ 30","unknown combinations retained but not credited");Check(day.ActiveSeconds==230,"estimate never changes actual activity");ShortcutSavings.LoadModel("0.25|0.5|2");savings=ShortcutSavings.Build(day);foreach(CrossChartRow r in savings.Chart)Check(r.Values[0]==0,"negative savings clamped");ShortcutSavings.LoadModel("NaN|0|2");Check(ShortcutSavings.MenuSeconds==.25,"invalid model ignored");ShortcutSavings.LoadModel("2|0.5|2");Check(ShortcutSavings.Build(null).Chart.Count==0,"no invented empty-day savings");Console.WriteLine("PASS: session identity, coverage conservation, legacy isolation, savings arithmetic, unknown combos and model validation");}}
