using System;using System.Drawing;using System.Diagnostics;using System.Threading;using KeyMouseStats;
internal static class ThemeOwnershipTests{
static int checks;static void Check(bool b,string s){if(!b)throw new Exception(s);checks++;}
static Image Wait(string name){Stopwatch w=Stopwatch.StartNew();Image image;while((image=ThemeImages.Get(name))==null){if(w.ElapsedMilliseconds>15000)throw new Exception(name);Thread.Sleep(5);}return image;}
[STAThread]static void Main(){try{Run();}catch(Exception e){Console.WriteLine(e.Message);Environment.ExitCode=1;}}
static void Run(){foreach(int theme in new[]{5,6,7,8,9,10,11}){Store.ThemeId=theme;string[] names=ThemeAssets.ForTheme(theme);Image[] refs=new Image[names.Length];for(int i=0;i<names.Length;i++)refs[i]=Wait(names[i]);int decoded=ThemeImages.DecodeCount;for(int pass=0;pass<5;pass++)for(int i=names.Length-1;i>=0;i--)Check(object.ReferenceEquals(refs[i],ThemeImages.Get(names[i])),"active theme original remains pinned");Check(ThemeImages.DecodeCount==decoded,"page revisits do not decode again");Check(ThemeImages.AllocatedBytes<=ThemeImages.Budget,"reserved plus published budget");}
for(int i=0;i<40;i++){Store.ThemeId=i%2==0?5:9;ThemeImages.EnsureTheme();}Store.ThemeId=9;Image atlas=Wait("BalatroBackgrounds"),icons=Wait("BalatroIcons");Thread.Sleep(100);Check(ThemeImages.Get("NikkiDream")==null,"stale generation cannot publish into current theme");Check(ThemeImages.AllocatedBytes<16L*1024*1024,"old jobs do not leak reservations");
using(Bitmap canvas=new Bitmap(1072,724))using(Graphics g=Graphics.FromImage(canvas)){
Rectangle src=new Rectangle(0,0,atlas.Width/2,atlas.Height/3);RectangleF bounds=new RectangleF(0,0,1072,724);NikkiArt.DrawCached(g,atlas,src,bounds,1,"background-test");
for(int i=0;i<300;i++)NikkiArt.DrawCached(g,icons,new Rectangle(0,0,icons.Width/4,icons.Height/4),new RectangleF(0,0,40+i%40,40+i%40),1,"icon-storm-"+i);
int built=NikkiArt.CacheBuilds;NikkiArt.DrawCached(g,atlas,src,bounds,1,"background-test");Check(NikkiArt.CacheBuilds==built,"icon churn cannot evict background surface");Check(NikkiArt.ScaledBytes<=40L*1024*1024,"scaled budget");
using(Bitmap source=new Bitmap(40,20)){using(Graphics paint=Graphics.FromImage(source)){paint.Clear(Color.Blue);using(SolidBrush red=new SolidBrush(Color.Red))paint.FillRectangle(red,0,0,20,20);}NikkiArt.DrawCached(g,source,new Rectangle(0,0,20,20),new RectangleF(0,0,20,20),1,"same-name");Check(canvas.GetPixel(10,10).R>200,"first atlas region");NikkiArt.DrawCached(g,source,new Rectangle(20,0,20,20),new RectangleF(0,0,20,20),1,"same-name");Check(canvas.GetPixel(10,10).B>200,"source rectangle participates in cache identity");}}
Store.ThemeId=0;NikkiArt.SyncTheme();Thread.Sleep(100);Check(ThemeImages.AllocatedBytes==0&&ThemeImages.ResidentBytes==0&&NikkiArt.ScaledBytes==0,"inactive theme releases originals and scaled surfaces");Console.WriteLine("PASS: "+checks+" theme ownership / stale completion / no re-decode / icon isolation / atlas identity checks");}}
